### ISSUE TITLE
VR headset experience for riding the bus

### ISSUE THREAD

**Issue by mateoclarke** [atxhack4change/2016-project-proposals#1]
## Short description of the idea (140 character tweet):
Imagine if every time you got on the bus, it was like riding a roller coaster to work :roller_coaster: 

## What is your project concept or idea? What challenge or opportunity will it solve?
Riding the bus is cool. Especially when you use [instabus.org](http://instabus.org). There's really no reason to bus upset. But imagine if you could fly to work on the bus. Or swim through the ocean? Our idea is to design the most fun commute you could image with cuttin' -edge virtual reality hardware.

## Who will benefit from your project? Describe the humans at the center of the problem - who are they? How would they benefit? Do you have photos of them? Or quotes?
These 4 dudes would benefit primarily. Maybe I should see if anyone else would benefit? Like the bus agency. Or people that actually ride the bus.

![vr](https://cloud.githubusercontent.com/assets/5697474/14228610/b51e9400-f8df-11e5-9334-b3425967a58e.gif)

## Issue area(s) relevant to your project idea:
- Arts & Culture
- Children & Youth
- Mobility/Transportation

## What is the current state of your project idea?

- I have an idea or concept of a solution, but have not yet prototyped or tested it

## Tell us more about the current state of your project idea.  Do you have any links to mockups, code, data or text?
Well, I kinda just thought of this. I probably need to do more research. And I have absolutely no experience with gaming, graphics, or virtual reality hardware. So there is probably a lot of things I have to learn there. But its a $1 million idea. Or maybe $2 million. I forgot...
:sparkles: 

## Tell us about yourself. What is your background? Why is this challenge important to you? Are you representing a group in submitting this project idea? 

Hey, thanks for asking! I'm Mateo, one of the core team leaders of Open Austin. This challenge isn't that important to me. I just wanted to provide a funny and stoopid project idea as an anti-pattern or bad example. There's no way you can do worse than me. 

- :man:

**Comment by amaliebarras** [comment]
🙌🏻

**Comment by mateoclarke** [comment]
this was just an 💩 example. Closing it out.
