### ISSUE TITLE
STEAM education

### ISSUE THREAD

**Issue by creativecornerarts** [atxhack4change/2016-project-proposals#25]
## Short description of the idea (140 character tweet):

Non-profit to promote STEAM (Science, Technology, Engineering, Art, Math) education for elementary-age kids.

## What is your project concept or idea? What challenge or opportunity will it solve?

The focus on STEAM education is gaining popularity, but it still remains far fetched to the children in financially challenged neighborhoods. Schools, teachers, parents in well to do areas have the resources and time to incorporate STEAM into regular curriculum or as part of extra-curricular activities. Parents in these areas invest their own time on a multitude of STEAM activities outside of school, for example, lead robotics teams, help with science projects and push their kids to participate in coding competitions. Compare this with the opportunities children in other areas, who are barely making it through school. Their parents don’t have the time, resources or the exposure to shuttle kids from one class to another. 

We want to make STEAM accessible and available to every child, irrespective of what school they go to. We believe that creativity and curiosity go hand in hand and we strive to nurture these skills in the individuals we come across. We want to offer an after school program, where the kids can focus on building artistic, scientific, social and personal skills. Our mission is to introduce and inculcate the love of STEAM in a fun loving, enjoyable and creative way. 

### Do you have photos of them? Or quotes?

Elementary age Kids 5 - 11 years old all over Austin. 
They will benefit by learning about the various STEAM areas of education by doing hands on projects,  irrespective of which part of Austin they live in. Elementary age kids are still impressionable, curious and have boundless imagination. This is the time to get them asking more questions like, “I wonder how the nurse gave me a shot so quickly?” or “How can my grandma see me on my mom’s phone?” or “Where does all the rain water go?” This is the time to answer their questions so that they find out that it’s school that makes all of these things possible.

We’ve done a few workshops in the past and have photos here:
http://creativecornerarts.com/gallery/

## Issue area(s) relevant to your project idea:

- Arts & Culture
- Children & Youth
- Economic Opportunity & Development
- Education

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it
- I tested a **prototype** and want to build it

### Do you have any links to news articles, text, mockups, code, or data?

We have conducted some workshops since November 2014, as and when our time permitted. We are now ready to make this bigger and offer a regular program starting Fall of this year. 
We are still in process of filing for our non-profit status.

We need help with our website. We want to make it easy to use, easy to find information. We want to make it visually appealing. We need to create a place where students and parents can go to find where and when our next workshops are going to be and register for them. 

We also need help with maintaining our pictures, newsletters, student databases, teacher databases, events - i.e. all the data that needs to be maintained. 

We need a place to post DIY projects where parents and students can go to figure out how to do something. We are envisioning a discussion forum for the future where they can post questions and answers and participate in an online discussion about projects they did or want to do.

### Are you representing a group in submitting this project idea? 

We are Creative Corner Arts: http://creativecornerarts.com/

Creative Corner Arts is co-founded by Meena Matai and Kirti Joshi. We are artists, Electrical Engineers and mothers. We felt the need to integrate curiosity and creativity for children. We decided to channel our artistic passions with a structured scientific approach towards the all rounded development of children. We are two people who are envisioning bringing about a big change in the world of education. If we can even make a positive impact in one child’s life we will consider ourselves successful.

**Comment by danielhonker** [comment]
Thanks for the submission, @creativecornerarts! I added some labels.

**Comment by polunsky** [comment]
I'll be at the STEAM event at Metz Elementary this Thursday (May 26, 2016) at 5:30 with a TTI exhibit. I'll try to visit with you there. If you're not aware of it, contact Metz Principal Martha Castillo at martha.i.castillo@austinisd.org

**Comment by ssharif1** [comment]
Hello Project Champion,

Please provide the following:
Full Name + Email Address 
You can comment here or send to ssharif1@stedwards.edu

We are going to be sending out a note + newsletter to our 372 (as of May 23) attendees sharing our submitted projects before the event and your hackers will want to know who you are. Additionally, we have PC-specific communication that we want to make sure that you are included on.

Thanks,
ATX H4C Staff

**Comment by creativecornerarts** [comment]
@polunsky Thanks! We are going to miss seeing you tomorrow at Metz Elementary. Hope to see you at future events. Thanks! Meena.

**Comment by mateoclarke** [comment]
Hi @creativecornerarts. Your project has been accepted!

Now that your project has been approved, here are some things we suggest you do next:
https://github.com/atxhack4change/2016-project-proposals#once-your-project-is-accepted-here-are-some-things-we-suggest-you-do-next

You will receive an email in the next few days asking you to confirming your speaking slot for the Saturday morning pitches. 

Please let us know if you will no longer be able to champion your project at the hackathon.

**Comment by danielhonker** [comment]
@creativecornerarts - you should have received an invite to join Slack. If you haven't already joined the team and seen the Slack channel for your project, it's #steam-edu. We'll be sending out an email with details on pitches soon.
