### ISSUE TITLE
Bots for a Change

### ISSUE THREAD

**Issue by fernandezcw** [atxhack4change/2016-project-proposals#32]
## Short description of the idea (140 character tweet):

Bots For A Change- A Facebook Messenger bot to help non-profits collect donations more efficiently.

## What is your project concept or idea? What challenge or opportunity will it solve?

It’s easy to like and share posts from the causes we believe in on Facebook. But it’s almost impossible to click on one of those posts and make a donation, especially if you’re trying to do it from a mobile device. While non-profits are great at creating awareness on Facebook, their non-optimized payment sites are hampering fund raising efforts. With 85% of web traffic coming from mobile and a huge portion of that from Facebook, non-profits need help building mobile-friendly payment solutions to fundraise successfully. Bots for A Change would leverage the Facebook Messenger platform to unlock mobile payments for non-profits.

## Who will benefit from your project? Describe the humans at the center of the problem - who are they?

Teresa Granillo, Executive Director of Con Mi Madre and the 300 young Latinas that are empowered by her organization.
 
Dylan Jones, Artistic Director of Anthropos Arts and the 150 at-risk students that receive free music lessons through the program.
 
Tony Jilek, VP of Marketing at Long Center for the Arts and all of the the local arts organizations it supports.
 
### How would they benefit? Can you tell their story?

Understaffed and with limited resources these non-profits work miracles to fundraise to make an impact in our society. A best-in-class mobile payment flow that taps into Facebook traffic would help them meet their goals more efficiently.

You can read more about these non-profits here:

http://www.conmimadre.org/about-us.html
http://anthroposarts.org/about/
http://thelongcenter.org/about/

Read about the FB Messenger SDK Here

https://developers.facebook.com/docs/messenger-platform

## Issue area(s) relevant to your project idea:

- Arts & Culture
- Children & Youth

## What is the current state of your project idea?

I have approached The Long Center, Con Mi Madre and Anthropos Arts. All of them are interested in the project and willing to explore the solution we develop. The three organizations have granted me admin access to their Facebook Pages and can serve as  beta testers.
 
I attended F8, studied the messenger SDK documentation and have an initial idea of how Messenger can solve the problem but am looking to collaborate with a team of designers and developers to find the best way to solve the problem.

### Are you representing a group in submitting this project idea? 

I am currently launching my own startup after three and a half years building and launching products at Spredfast and RebelMouse. 

Read more about me on my socialCV http://www.fernandezcw.com/social_cv/

Con Mi Madre, Anthropos and The Long Center are three non-profits that are close to my heart. I'd love to help build a great team to solve this problem on their behalf and learn about what is possible with Messenger SDK while we're at it.

**Comment by mateoclarke** [comment]
This looks like a duplicate. I'm going to close this out, but please make any edits or comments on #31.

**Comment by fernandezcw** [comment]
thx- sorry about that

On Mon, May 23, 2016 at 11:11 PM, Mateo Clarke <notifications@github.com>
wrote:

> This looks like a duplicate. I'm going to close this out, but please make
> any edits or comments on #31
> <https://github.com/atxhack4change/2016-project-proposals/issues/31>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/atxhack4change/2016-project-proposals/issues/32#issuecomment-221161852>
>



-- 
Miguel Fernández
Social CV <http://www.fernandezcw.com/Social_CV/>
Puerto Rico Travel Blog <https://www.rebelmouse.com/airborinquen/>
Twitter <https://twitter.com/fernandezcw>
