### ISSUE TITLE
Refreshing the Friendly Manual

### ISSUE THREAD

**Issue by McCnnll** [atxhack4change/2016-project-proposals#34]
## Short description of the idea (140 character tweet):

Updating the how-to documentation for the city data portal to reflect its new features and redesign.

## What is your project concept or idea? What challenge or opportunity will it solve?

For citizen analysts and civic hackers, the city data portal may be difficult to understand, particularly now that its interface has changed signficantly. How-to documents could aid new users in learning how to use the data that the city publishes. This project may ease the learning curve for non-technical users by showing how to complete concrete tasks. It also addresses the interface changes in the portal. 

## Who will benefit from your project? Describe the humans at the center of the problem - who are they? 
The primary beneficiaries of this project are members of the general public interested in open data, but need some guidance on how to start conducting analysis or using data in their own applications. These may be non-technical users who have some familiarity with data manipulation in common software such as Excel.

This project would also provide an opportunity to engage non-technical participants at the ATX Hack for Change since it does not involving coding or design. Non-technical participants could contribute to this project through writing, proofreading, and testing documentation.

## Issue area(s) relevant to your project idea:

- Open Government/Transparency
- Civic Engagememt
- Economic Opportunity & Development
- Other

## What is the current state of your project idea?

- This is a necessary update to an existing project.

## Tell us more about the current state of your project idea.

- This would be an extension of the [documentation effort from the 2014 hackathon, which is currently available on wikispaces](https://atxdataportal.wikispaces.com). This project attracted significant attention, including from the open-data team at the City of New York, which has referred to the Austin effort as its "open-data bible."

## Tell us about yourself. 

- I'm an English major with an interest in technology, and I believe it's important for the civic tech community to engage non-technical groups with projects like these. This project could expand the reach of open data by affording non-technical folks an opportunity to engage in civic tech projects and provide introductory materials to those who may feel intimidated by the data portal or other data sources.

**Comment by ssharif1** [comment]
Morning, 

Please provide the following today so we can finalize our project review:
Full Name + Email Address 
You can comment here or send to ssharif1@stedwards.edu

Thanks,
ATX H4C Staff

**Comment by ssharif1** [comment]
You're in, @McCnnll ! We invite you to pitch your project at the 2016 ATX Hack for Change!

Now that your project has been approved, here are some things we suggest you do next:
https://github.com/atxhack4change/2016-project-proposals#once-your-project-is-accepted-here-are-some-things-we-suggest-you-do-next

ACTION ITEM: You haven't sent us your full name + email, please send to: ssharif1@stedwards.edu

You will receive an email shortly regarding you speaking slot for the Saturday morning pitches. Please let us know if you will no longer be able to champion your project at the hackathon.

**Comment by McCnnll** [comment]
![english_major_armadillo](https://cloud.githubusercontent.com/assets/7535602/15556838/8cffdb02-2295-11e6-9506-3876869f2acc.jpg)

**Comment by danielhonker** [comment]
@McCnnll - you should have received an invite to join Slack. If you haven't already joined the team and seen the Slack channel for your project, it's #citydataportal. We'll be sending out an email with details on pitches soon.

**Comment by mateoclarke** [comment]
Hey Chris, just letting you know that I've marked this project as needed a new lead and communicated to the rest of the team that you are looking for a replacement. Let us know if you need to withdraw the project.

Thanks!
Mateo

cc/ @danielhonker @ssharif1
