### ISSUE TITLE
Water Conservation Calculator

### ISSUE THREAD

**Issue by CiaoAlanna** [atxhack4change/2016-project-proposals#37]
## Short description of the idea (140 character tweet):
Build a JavaScript calculator based on new Water Conservation water restrictions that can automatically generate an irrigation schedule to help conserve water. (138 word count)

#NewConservationStage #AustinWater #MakeitLast #WaterForward

## What is your project concept or idea? What challenge or opportunity will it solve?
A new, simple and intuitive, irrigation calculator can generate a custom schedule and help our community:

**- Save Water** - Ensuring run times are correct for an irrigation system means eliminating water waste while still growing healthy landscapes.

**- Save Money** - By using less water, you lower your water bill. Over time this savings can result in significant sums of money.

## Who will benefit from your project? Describe the humans at the center of the problem - who are they?
Anyone with an irrigation system, this could include: home-owners, businesses, commercial properties, and schools. 

### How would they benefit? Can you tell their story?
- This could benefit the homeowner who always sees water running into the street after her sprinkler system goes off and is tired of not only wasting water, but high water bills.

- This could benefit the business owner that doesn’t know when his watering day is at his commercial property, and also wants to save money.

- This could benefit the school that has multiple zones to water, but wants to practice water conservation, but still have a lush landscape for students to enjoy.

### Do you have photos of them? Or quotes?
Stock photos are available 

## Issue area(s) relevant to your project idea:
- Education
- Environment & Sustainability
- Open Government/Transparency

## What is the current state of your project idea?
- I tested a **prototype** and want to build it

## Tell us more about the current state of your project idea.
The code is already in ColdFusion, it is just a matter of writing it in JavaScript, creating icons, and making it super-easy-to-use. 

### Do you have any links to news articles, text, mockups, code, or data?
Current Runtime [Calculator](http://www.austintexas.gov/water/conservation/irrigation/calculator.cfm)

## Tell us about yourself. 
I am the marketing strategist for Austin Water, with the City of Austin. My latest project is a brand refresh of the department and a redesign of AustinWater.org using customer and user experience journey mapping. I have been a City of Austin employee for 12 years and have a background in public relations, digital communication, community engagement and event management.

### What is your background? Why is this challenge important to you? 
This project is important to me in that it offers a valuable tool to the community to help conserve water. This project also falls in line with the mission of Austin Water which is to provide safe, reliable, high quality, sustainable, and affordable water service to our customers so that all community needs for water services are met.

**Comment by ssharif1** [comment]
Morning, 

Please provide the following today so we can finalize our project review:
Full Name + Email Address 

You can comment here or send to ssharif1@stedwards.edu

Thanks,
ATX H4C Staff

**Comment by ssharif1** [comment]
Evening @CiaoAlanna ,

Please provide the following today so we can finalize our project review:
Full Name + Email Address

You can comment here or send to ssharif1@stedwards.edu

Thanks,
ATX H4C Staff

**Comment by danielhonker** [comment]
@ssharif1 I know @CiaoAlanna. I'll confirm the project with her and enter her contact details.

@CiaoAlanna - Consider your project accepted. We invite you to pitch at the ATX Hack for Change!

Now that your project has been approved, here are some things we suggest you do next:
https://github.com/atxhack4change/2016-project-proposals#once-your-project-is-accepted-here-are-some-things-we-suggest-you-do-next

You will receive an email in the next few days regarding your speaking slot for the Saturday morning pitches. Please let us know if you will no longer be able to champion your project at the hackathon.

**Comment by danielhonker** [comment]
@CiaoAlanna - The Slack channel for your project is #watercalculator. We'll be sending out an email with details on pitches soon.

**Comment by CiaoAlanna** [comment]
@ssharif1 @danielhonker Unfortunately I have been told that we need to pull this project from the ATX Hack for Change. :-1:
