### ISSUE TITLE
Bike Safety

### ISSUE THREAD

**Issue by Sahedeva** [atxhack4change/2016-project-proposals#41]
## Short description of the idea (140 character tweet):

The problem is that there is no place where bikers can share and collect data about bike safety, use and infrastructure.

## What is your project concept or idea? What challenge or opportunity will it solve?

Making an app that will allow bike riders to share knowledge of safe vs dangerous bike routes that will also be shared with the city's bicycle safety department. This will also allow for community input for urban planning - and give more realtime information to help with Austin's vision zero plan.

## Who will benefit from your project? Describe the humans at the center of the problem - who are they? 
Potential Bikers
Serious Bikers
Pedestrians
Car and Bike Commuters
Tourist Bikers
### How would they benefit? Can you tell their story?
The entire purpose of the app is to allow everyday users to tell their story to each other as well as to the city. With knowledge comes power to solve problems.

### Do you have photos of them? Or quotes?
No but this shouldn't be too hard to obtain - there are tons of people who bike regularly to work and for recreation in Austin.

## Issue area(s) relevant to your project idea:
- Economic Opportunity & Development
- Education
- Environment & Sustainability
- Health
- Mobility/Transportation
- Neighborhoods
- Open Government/Transparency
- Public Safety

## What is the current state of your project idea?
We completed a Civic Tech Project Planning Canvass.
- I understand the **challenge** well but don’t yet have ideas for a solution

## Tell us more about the current state of your project idea.
It is still in its infancy but there were a lot of good ideas that we had at CodeAcross.

### Do you have any links to news articles, text, mockups, code, or data?
The city's vision zero plan has definitely brought some energy to this issue. 
http://kut.org/post/what-exactly-vision-zero-plan-and-why-does-austin-need-one

### What is your background? Why is this challenge important to you? 
I am a recent transplant to the city and was biking 5 1/2 miles each way to commute to downtown, so this issue definitely spoke to me. Several places along my route are extremely unsafe with no lighting and no bike lanes.
### Are you representing a group in submitting this project idea? 
I am representing the Bike Safety Group from CodeAcross.
![3237836a-e2e3-11e5-9a39-ea47558b4127](https://cloud.githubusercontent.com/assets/13663007/15491710/dc446da8-2138-11e6-9471-5c0c1b904f71.jpg)

**Comment by mateoclarke** [comment]
Hey @Sahedeva, just making sure you meant to close out this proposal. 

Let us know by 5/27 if you are still interested in pitching this project at the hackathon on Saturday morning.
