### ISSUE TITLE
Complete and reliable Austin bus system.

### ISSUE THREAD

**Issue by anthonyarmendariz** [atxhack4change/2016-project-proposals#7]
Picks up every 5-10m city wide. Expressbusses (fewer stops). Extremely more stops.

Mobile applications for real time tracking and payment. Tracks popular spots and underserved stops.

**Comment by mateoclarke** [comment]
Hi @anthonyarmendariz.

Can you please use the linked [project proposal template](https://github.com/atxhack4change/2016-project-proposals/blob/master/ISSUE_TEMPLATE.md) to give everyone a better idea for the idea you are proposing?

It is important for volunteers on the team you would lead to understand some basics about the project you are proposing before they decide to work on any solution.

https://github.com/atxhack4change/2016-project-proposals/blob/master/ISSUE_TEMPLATE.md

**Comment by ssharif1** [comment]
### ACTION NEEDED 

Hello Project Champion, 

Please provide the following:
Full Name + Email Address 
You can comment here or send to ssharif1@stedwards.edu 

We are going to be sending out a note + newsletter to our 345 (as of May 18) attendees sharing our submitted projects before the event and your hackers will want to know who you are. Additionally, we have PC-specific communication that we want to make sure that you are included on.

Thanks,
ATX H4C Staff

**Comment by mateoclarke** [comment]
Hi @anthonyarmendariz. Unfortunately, this project proposal is incomplete and didn't follow the [proposal template](https://github.com/atxhack4change/2016-project-proposals/blob/master/ISSUE_TEMPLATE.md).
